spring.application.name=backend
server.port=8080

# Configuración de Firebase
# El archivo serviceAccountKey.json debe estar en src/main/resources/
# (Ignorado en Git por seguridad)

# Desactivamos banners innecesarios
spring.main.banner-mode=off
logging.level.org.springframework.web=INFO
